[package]
name = "oxymp-main"
version = "0.1.0"
edition = "2021"

[dependencies]
oxymp = { version = "0.1.0", path = "oxymp-derive" }
regex = "1.10.6"
oxymp_util = { version = "0.1.0", path = "oxymp-util" }
